steps:
  # 1) Build the image (from ./backend) and tag it
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - build
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'
      - '.'

  # 2) Push the image to Artifact Registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'

  # 3) Deploy to Cloud Run, mit Secret-Injection
  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - beta
      - run
      - deploy
      - mealo
      - --project=$PROJECT_ID
      - --region=europe-west3
      - --platform=managed
      - --image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA
      # vorheriges ENV entfernen, da es nun als Secret kommt
      - --remove-env-vars=GOOGLE_APPLICATION_CREDENTIALS
      # Secret-Manager: als ENV injizieren
      - --update-secrets=GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account:latest,OPENAI_API_KEY=openai-api-key:latest
      # IAM Service Account für Cloud Run
      - --service-account=1095476512586-compute@developer.gserviceaccount.com
      - --quiet

# Nur Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY

# Artefakt-Registry
images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'
