steps:
  # 1) Build the image (from ./backend) und taggen
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - build
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'
      - '.'

  # 2) Push the image to Artifact Registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'

  # 3) Deploy zu Cloud Run, mit Secret-Injection
  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - beta
      - run
      - deploy
      - mealo
      - --project=$PROJECT_ID
      - --region=europe-west3
      - --platform=managed
      - --image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA
      # Injektion der gewünschten Secrets als Umgebungsvariablen.
      # Da DATABASE_URL bereits ein Secret ist, muss es hier über --update-secrets übergeben werden.
      # Stellen Sie sicher, dass 'mealo-database-url' der korrekte Name des Secrets im Secret Manager ist.
      - --update-secrets=GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,DATABASE_URL=mealo-database-url:latest
      # Fügen Sie ein Volume für GCS_KEY_FILE hinzu und mounten Sie es.
      # Ersetzen Sie 'gcs-media-uploader-key' durch den tatsächlichen Namen Ihres Secrets im Secret Manager.
      # Dies setzt voraus, dass der INHALT der Datei media-uploader-key.json im Secret Manager gespeichert ist.
      - --add-volume=name=gcs-key-volume,secret=gcs-media-uploader-key
      - --add-volume-mount=volume=gcs-key-volume,path=/app/certs/media-uploader-key.json # Pfad im Container, wo die Datei sein soll
      # Setzen anderer Umgebungsvariablen, die keine Secrets sind (z.B. BUCKET_NAME)
      # und weisen Sie GCS_KEY_FILE auf den gemounteten Pfad.
      - --set-env-vars=BUCKET_NAME=mealo-media,GCS_KEY_FILE=/app/certs/media-uploader-key.json
      # Service-Account für Cloud Run
      - --service-account=1095476512586-compute@developer.gserviceaccount.com
      - --quiet

# Nur Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY

# Artefakt-Registry
images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'
