steps:
  # 1) Build the Docker image from ./backend
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'
      - '.'

  # 2) Push the image up to Artifact Registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'

  # 3) Deploy to Cloud Run
  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'mealo'
      - '--project=$PROJECT_ID'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'
      # Normale Umgebungsvariablen
      - '--set-env-vars=BUCKET_NAME=mealo-media'
      # Nur ENV-Vars, die keine Dateipfade sind
      - '--update-secrets=DATABASE_URL=DATABASE_URL:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest' # <-- OPENAI_API_KEY hinzugefügt, nur ENV-Vars hier
      # Secret Volumes für Schlüsseldateien
      # Stellen Sie sicher, dass diese Secrets (firebase-service-account, media-uploader-key)
      # den Inhalt der jeweiligen JSON-Dateien enthalten.
      - '--add-volume=name=firebase-sa-volume,type=secret,secret=firebase-service-account'
      - '--add-volume-mount=volume=firebase-sa-volume,mount-path=/app/certs/firebase-service-account.json' # <-- Beispielpfad im Container
      - '--add-volume=name=gcs-key-volume,type=secret,secret=media-uploader-key' # <-- "media-uploader-key" aus Ihrer Abbildung
      - '--add-volume-mount=volume=gcs-key-volume,mount-path=/app/certs/media-uploader-key.json' # <-- Beispielpfad im Container
      # Setzen der Umgebungsvariablen auf die gemounteten Pfade
      - '--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/certs/firebase-service-account.json,GCS_KEY_FILE=/app/certs/media-uploader-key.json,BUCKET_NAME=mealo-media'
      - '--service-account=1095476512586-compute@developer.gserviceaccount.com'
      - '--quiet'

# Only Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY

# Tell Cloud Build to expect this image tag
images:
  - 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/mealo/mealo:$COMMIT_SHA'